### PR TITLE
Fixed the readme's formatting for github markdown

### PR DESCRIPTION
**Pull request by timlyo**

### CODE REVIEW

**Comment by tuomasjjrasanen** [comment]
I'd prefer reStructuredText. Actually, README is almost valid `rst` already.

**Comment by timlyo** [comment]
Might be worth changing the extension name then so that github renders it.

**Comment by tuomasjjrasanen** [comment]
Yes, and making few tweaks to the markup itself. If you want and know `rst`, I'll be happy to receive a pull request. But if not, I'll do it myself.

**Comment by tuomasjjrasanen** [comment]
I'll close this, README has been converted to reStructuredText.

**Pull request closed without merging**
