### PR TITLE
Expose uinput file descriptor on Device

### PR DESCRIPTION
**Pull request by goncalopp**
This is useful for dropping root privileges (setuid).

### CODE REVIEW

**Comment by tuomasjjrasanen** [comment]
Yep, it's a good idea to expose a function for opening fd, but I'm not sure it should be Device's business actually. I would rather just add a function (perhaps called `fdopen()`) to the module scope and use it instead. Then it would be called like this:

    fd = uinput.fdopen()

That is prettier in my opinion (like `os.fdopen()`).
So basically just assign `_libsuinput.suinput_open` to `fdopen` in the top-level code. What do you think?

**Comment by goncalopp** [comment]
SGTM.
But how would we create a Device with an already existing fd? Do you 
plan to pass it as an optional argument to Device.__init__?

**Comment by tuomasjjrasanen** [comment]
Yep, just like you proposed. Passing fd as a kwarg is fine, defaulting to `None`.

**Comment by goncalopp** [comment]
I actually had forgotten this was a pull request! I'll work on the changes you proposed and let you know

**Comment by tuomasjjrasanen** [comment]
Thanks a lot!

**Pull request merged**
